services:
  db:
    image: mysql:latest
    container_name: lego-manager-db
    hostname: lego-manager-db
    env_file:
     - .env.db
    ports:
      - 3306:3306
    volumes:
      - ./lego-manager-db-data:/var/lib/mysql
      - ./lego-manager-db-conf:/etc/mysql/conf.d
    restart: always

  backend:
    build:
      context: back
      dockerfile: Dockerfile
    container_name: lego-manager-backend
    hostname: lego-manager-backend
    volumes:
      - ./lego-manager-backend-images:/back/uploads/images
      - ./lego-manager-backend-instructions:/back/uploads/instructions
    restart: always
    ports:
       - 3001:3000
    env_file:
      - .env.backend
    depends_on:
      - db

  frontend:
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - 5173:3000
    container_name: lego-manager-frontend
    hostname: lego-manager-frontend
    restart: always
    depends_on:
      - backend
    environment:
      - ORIGIN=${ORIGIN}
      - BODY_SIZE_LIMIT=Infinity
